package com.seaboxdata.sdps.job.admin.core.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SdpsClusterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sdps_cluster
     *
     * @mbg.generated Fri Dec 24 15:33:19 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sdps_cluster
     *
     * @mbg.generated Fri Dec 24 15:33:19 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sdps_cluster
     *
     * @mbg.generated Fri Dec 24 15:33:19 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdps_cluster
     *
     * @mbg.generated Fri Dec 24 15:33:19 CST 2021
     */
    public SdpsClusterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdps_cluster
     *
     * @mbg.generated Fri Dec 24 15:33:19 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdps_cluster
     *
     * @mbg.generated Fri Dec 24 15:33:19 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdps_cluster
     *
     * @mbg.generated Fri Dec 24 15:33:19 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdps_cluster
     *
     * @mbg.generated Fri Dec 24 15:33:19 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdps_cluster
     *
     * @mbg.generated Fri Dec 24 15:33:19 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdps_cluster
     *
     * @mbg.generated Fri Dec 24 15:33:19 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdps_cluster
     *
     * @mbg.generated Fri Dec 24 15:33:19 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdps_cluster
     *
     * @mbg.generated Fri Dec 24 15:33:19 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdps_cluster
     *
     * @mbg.generated Fri Dec 24 15:33:19 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdps_cluster
     *
     * @mbg.generated Fri Dec 24 15:33:19 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sdps_cluster
     *
     * @mbg.generated Fri Dec 24 15:33:19 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andClusterIdIsNull() {
            addCriterion("cluster_id is null");
            return (Criteria) this;
        }

        public Criteria andClusterIdIsNotNull() {
            addCriterion("cluster_id is not null");
            return (Criteria) this;
        }

        public Criteria andClusterIdEqualTo(Integer value) {
            addCriterion("cluster_id =", value, "clusterId");
            return (Criteria) this;
        }

        public Criteria andClusterIdNotEqualTo(Integer value) {
            addCriterion("cluster_id <>", value, "clusterId");
            return (Criteria) this;
        }

        public Criteria andClusterIdGreaterThan(Integer value) {
            addCriterion("cluster_id >", value, "clusterId");
            return (Criteria) this;
        }

        public Criteria andClusterIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cluster_id >=", value, "clusterId");
            return (Criteria) this;
        }

        public Criteria andClusterIdLessThan(Integer value) {
            addCriterion("cluster_id <", value, "clusterId");
            return (Criteria) this;
        }

        public Criteria andClusterIdLessThanOrEqualTo(Integer value) {
            addCriterion("cluster_id <=", value, "clusterId");
            return (Criteria) this;
        }

        public Criteria andClusterIdIn(List<Integer> values) {
            addCriterion("cluster_id in", values, "clusterId");
            return (Criteria) this;
        }

        public Criteria andClusterIdNotIn(List<Integer> values) {
            addCriterion("cluster_id not in", values, "clusterId");
            return (Criteria) this;
        }

        public Criteria andClusterIdBetween(Integer value1, Integer value2) {
            addCriterion("cluster_id between", value1, value2, "clusterId");
            return (Criteria) this;
        }

        public Criteria andClusterIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cluster_id not between", value1, value2, "clusterId");
            return (Criteria) this;
        }

        public Criteria andClusterPasswdIsNull() {
            addCriterion("cluster_passwd is null");
            return (Criteria) this;
        }

        public Criteria andClusterPasswdIsNotNull() {
            addCriterion("cluster_passwd is not null");
            return (Criteria) this;
        }

        public Criteria andClusterPasswdEqualTo(String value) {
            addCriterion("cluster_passwd =", value, "clusterPasswd");
            return (Criteria) this;
        }

        public Criteria andClusterPasswdNotEqualTo(String value) {
            addCriterion("cluster_passwd <>", value, "clusterPasswd");
            return (Criteria) this;
        }

        public Criteria andClusterPasswdGreaterThan(String value) {
            addCriterion("cluster_passwd >", value, "clusterPasswd");
            return (Criteria) this;
        }

        public Criteria andClusterPasswdGreaterThanOrEqualTo(String value) {
            addCriterion("cluster_passwd >=", value, "clusterPasswd");
            return (Criteria) this;
        }

        public Criteria andClusterPasswdLessThan(String value) {
            addCriterion("cluster_passwd <", value, "clusterPasswd");
            return (Criteria) this;
        }

        public Criteria andClusterPasswdLessThanOrEqualTo(String value) {
            addCriterion("cluster_passwd <=", value, "clusterPasswd");
            return (Criteria) this;
        }

        public Criteria andClusterPasswdLike(String value) {
            addCriterion("cluster_passwd like", value, "clusterPasswd");
            return (Criteria) this;
        }

        public Criteria andClusterPasswdNotLike(String value) {
            addCriterion("cluster_passwd not like", value, "clusterPasswd");
            return (Criteria) this;
        }

        public Criteria andClusterPasswdIn(List<String> values) {
            addCriterion("cluster_passwd in", values, "clusterPasswd");
            return (Criteria) this;
        }

        public Criteria andClusterPasswdNotIn(List<String> values) {
            addCriterion("cluster_passwd not in", values, "clusterPasswd");
            return (Criteria) this;
        }

        public Criteria andClusterPasswdBetween(String value1, String value2) {
            addCriterion("cluster_passwd between", value1, value2, "clusterPasswd");
            return (Criteria) this;
        }

        public Criteria andClusterPasswdNotBetween(String value1, String value2) {
            addCriterion("cluster_passwd not between", value1, value2, "clusterPasswd");
            return (Criteria) this;
        }

        public Criteria andClusterNameIsNull() {
            addCriterion("cluster_name is null");
            return (Criteria) this;
        }

        public Criteria andClusterNameIsNotNull() {
            addCriterion("cluster_name is not null");
            return (Criteria) this;
        }

        public Criteria andClusterNameEqualTo(String value) {
            addCriterion("cluster_name =", value, "clusterName");
            return (Criteria) this;
        }

        public Criteria andClusterNameNotEqualTo(String value) {
            addCriterion("cluster_name <>", value, "clusterName");
            return (Criteria) this;
        }

        public Criteria andClusterNameGreaterThan(String value) {
            addCriterion("cluster_name >", value, "clusterName");
            return (Criteria) this;
        }

        public Criteria andClusterNameGreaterThanOrEqualTo(String value) {
            addCriterion("cluster_name >=", value, "clusterName");
            return (Criteria) this;
        }

        public Criteria andClusterNameLessThan(String value) {
            addCriterion("cluster_name <", value, "clusterName");
            return (Criteria) this;
        }

        public Criteria andClusterNameLessThanOrEqualTo(String value) {
            addCriterion("cluster_name <=", value, "clusterName");
            return (Criteria) this;
        }

        public Criteria andClusterNameLike(String value) {
            addCriterion("cluster_name like", value, "clusterName");
            return (Criteria) this;
        }

        public Criteria andClusterNameNotLike(String value) {
            addCriterion("cluster_name not like", value, "clusterName");
            return (Criteria) this;
        }

        public Criteria andClusterNameIn(List<String> values) {
            addCriterion("cluster_name in", values, "clusterName");
            return (Criteria) this;
        }

        public Criteria andClusterNameNotIn(List<String> values) {
            addCriterion("cluster_name not in", values, "clusterName");
            return (Criteria) this;
        }

        public Criteria andClusterNameBetween(String value1, String value2) {
            addCriterion("cluster_name between", value1, value2, "clusterName");
            return (Criteria) this;
        }

        public Criteria andClusterNameNotBetween(String value1, String value2) {
            addCriterion("cluster_name not between", value1, value2, "clusterName");
            return (Criteria) this;
        }

        public Criteria andClusterShowNameIsNull() {
            addCriterion("cluster_show_name is null");
            return (Criteria) this;
        }

        public Criteria andClusterShowNameIsNotNull() {
            addCriterion("cluster_show_name is not null");
            return (Criteria) this;
        }

        public Criteria andClusterShowNameEqualTo(String value) {
            addCriterion("cluster_show_name =", value, "clusterShowName");
            return (Criteria) this;
        }

        public Criteria andClusterShowNameNotEqualTo(String value) {
            addCriterion("cluster_show_name <>", value, "clusterShowName");
            return (Criteria) this;
        }

        public Criteria andClusterShowNameGreaterThan(String value) {
            addCriterion("cluster_show_name >", value, "clusterShowName");
            return (Criteria) this;
        }

        public Criteria andClusterShowNameGreaterThanOrEqualTo(String value) {
            addCriterion("cluster_show_name >=", value, "clusterShowName");
            return (Criteria) this;
        }

        public Criteria andClusterShowNameLessThan(String value) {
            addCriterion("cluster_show_name <", value, "clusterShowName");
            return (Criteria) this;
        }

        public Criteria andClusterShowNameLessThanOrEqualTo(String value) {
            addCriterion("cluster_show_name <=", value, "clusterShowName");
            return (Criteria) this;
        }

        public Criteria andClusterShowNameLike(String value) {
            addCriterion("cluster_show_name like", value, "clusterShowName");
            return (Criteria) this;
        }

        public Criteria andClusterShowNameNotLike(String value) {
            addCriterion("cluster_show_name not like", value, "clusterShowName");
            return (Criteria) this;
        }

        public Criteria andClusterShowNameIn(List<String> values) {
            addCriterion("cluster_show_name in", values, "clusterShowName");
            return (Criteria) this;
        }

        public Criteria andClusterShowNameNotIn(List<String> values) {
            addCriterion("cluster_show_name not in", values, "clusterShowName");
            return (Criteria) this;
        }

        public Criteria andClusterShowNameBetween(String value1, String value2) {
            addCriterion("cluster_show_name between", value1, value2, "clusterShowName");
            return (Criteria) this;
        }

        public Criteria andClusterShowNameNotBetween(String value1, String value2) {
            addCriterion("cluster_show_name not between", value1, value2, "clusterShowName");
            return (Criteria) this;
        }

        public Criteria andStorageResourceIdIsNull() {
            addCriterion("storage_resource_id is null");
            return (Criteria) this;
        }

        public Criteria andStorageResourceIdIsNotNull() {
            addCriterion("storage_resource_id is not null");
            return (Criteria) this;
        }

        public Criteria andStorageResourceIdEqualTo(Integer value) {
            addCriterion("storage_resource_id =", value, "storageResourceId");
            return (Criteria) this;
        }

        public Criteria andStorageResourceIdNotEqualTo(Integer value) {
            addCriterion("storage_resource_id <>", value, "storageResourceId");
            return (Criteria) this;
        }

        public Criteria andStorageResourceIdGreaterThan(Integer value) {
            addCriterion("storage_resource_id >", value, "storageResourceId");
            return (Criteria) this;
        }

        public Criteria andStorageResourceIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("storage_resource_id >=", value, "storageResourceId");
            return (Criteria) this;
        }

        public Criteria andStorageResourceIdLessThan(Integer value) {
            addCriterion("storage_resource_id <", value, "storageResourceId");
            return (Criteria) this;
        }

        public Criteria andStorageResourceIdLessThanOrEqualTo(Integer value) {
            addCriterion("storage_resource_id <=", value, "storageResourceId");
            return (Criteria) this;
        }

        public Criteria andStorageResourceIdIn(List<Integer> values) {
            addCriterion("storage_resource_id in", values, "storageResourceId");
            return (Criteria) this;
        }

        public Criteria andStorageResourceIdNotIn(List<Integer> values) {
            addCriterion("storage_resource_id not in", values, "storageResourceId");
            return (Criteria) this;
        }

        public Criteria andStorageResourceIdBetween(Integer value1, Integer value2) {
            addCriterion("storage_resource_id between", value1, value2, "storageResourceId");
            return (Criteria) this;
        }

        public Criteria andStorageResourceIdNotBetween(Integer value1, Integer value2) {
            addCriterion("storage_resource_id not between", value1, value2, "storageResourceId");
            return (Criteria) this;
        }

        public Criteria andCalcResourceIdIsNull() {
            addCriterion("calc_resource_id is null");
            return (Criteria) this;
        }

        public Criteria andCalcResourceIdIsNotNull() {
            addCriterion("calc_resource_id is not null");
            return (Criteria) this;
        }

        public Criteria andCalcResourceIdEqualTo(Integer value) {
            addCriterion("calc_resource_id =", value, "calcResourceId");
            return (Criteria) this;
        }

        public Criteria andCalcResourceIdNotEqualTo(Integer value) {
            addCriterion("calc_resource_id <>", value, "calcResourceId");
            return (Criteria) this;
        }

        public Criteria andCalcResourceIdGreaterThan(Integer value) {
            addCriterion("calc_resource_id >", value, "calcResourceId");
            return (Criteria) this;
        }

        public Criteria andCalcResourceIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("calc_resource_id >=", value, "calcResourceId");
            return (Criteria) this;
        }

        public Criteria andCalcResourceIdLessThan(Integer value) {
            addCriterion("calc_resource_id <", value, "calcResourceId");
            return (Criteria) this;
        }

        public Criteria andCalcResourceIdLessThanOrEqualTo(Integer value) {
            addCriterion("calc_resource_id <=", value, "calcResourceId");
            return (Criteria) this;
        }

        public Criteria andCalcResourceIdIn(List<Integer> values) {
            addCriterion("calc_resource_id in", values, "calcResourceId");
            return (Criteria) this;
        }

        public Criteria andCalcResourceIdNotIn(List<Integer> values) {
            addCriterion("calc_resource_id not in", values, "calcResourceId");
            return (Criteria) this;
        }

        public Criteria andCalcResourceIdBetween(Integer value1, Integer value2) {
            addCriterion("calc_resource_id between", value1, value2, "calcResourceId");
            return (Criteria) this;
        }

        public Criteria andCalcResourceIdNotBetween(Integer value1, Integer value2) {
            addCriterion("calc_resource_id not between", value1, value2, "calcResourceId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andClusterStatusIdIsNull() {
            addCriterion("cluster_status_id is null");
            return (Criteria) this;
        }

        public Criteria andClusterStatusIdIsNotNull() {
            addCriterion("cluster_status_id is not null");
            return (Criteria) this;
        }

        public Criteria andClusterStatusIdEqualTo(Integer value) {
            addCriterion("cluster_status_id =", value, "clusterStatusId");
            return (Criteria) this;
        }

        public Criteria andClusterStatusIdNotEqualTo(Integer value) {
            addCriterion("cluster_status_id <>", value, "clusterStatusId");
            return (Criteria) this;
        }

        public Criteria andClusterStatusIdGreaterThan(Integer value) {
            addCriterion("cluster_status_id >", value, "clusterStatusId");
            return (Criteria) this;
        }

        public Criteria andClusterStatusIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cluster_status_id >=", value, "clusterStatusId");
            return (Criteria) this;
        }

        public Criteria andClusterStatusIdLessThan(Integer value) {
            addCriterion("cluster_status_id <", value, "clusterStatusId");
            return (Criteria) this;
        }

        public Criteria andClusterStatusIdLessThanOrEqualTo(Integer value) {
            addCriterion("cluster_status_id <=", value, "clusterStatusId");
            return (Criteria) this;
        }

        public Criteria andClusterStatusIdIn(List<Integer> values) {
            addCriterion("cluster_status_id in", values, "clusterStatusId");
            return (Criteria) this;
        }

        public Criteria andClusterStatusIdNotIn(List<Integer> values) {
            addCriterion("cluster_status_id not in", values, "clusterStatusId");
            return (Criteria) this;
        }

        public Criteria andClusterStatusIdBetween(Integer value1, Integer value2) {
            addCriterion("cluster_status_id between", value1, value2, "clusterStatusId");
            return (Criteria) this;
        }

        public Criteria andClusterStatusIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cluster_status_id not between", value1, value2, "clusterStatusId");
            return (Criteria) this;
        }

        public Criteria andClusterSourceIsNull() {
            addCriterion("cluster_source is null");
            return (Criteria) this;
        }

        public Criteria andClusterSourceIsNotNull() {
            addCriterion("cluster_source is not null");
            return (Criteria) this;
        }

        public Criteria andClusterSourceEqualTo(String value) {
            addCriterion("cluster_source =", value, "clusterSource");
            return (Criteria) this;
        }

        public Criteria andClusterSourceNotEqualTo(String value) {
            addCriterion("cluster_source <>", value, "clusterSource");
            return (Criteria) this;
        }

        public Criteria andClusterSourceGreaterThan(String value) {
            addCriterion("cluster_source >", value, "clusterSource");
            return (Criteria) this;
        }

        public Criteria andClusterSourceGreaterThanOrEqualTo(String value) {
            addCriterion("cluster_source >=", value, "clusterSource");
            return (Criteria) this;
        }

        public Criteria andClusterSourceLessThan(String value) {
            addCriterion("cluster_source <", value, "clusterSource");
            return (Criteria) this;
        }

        public Criteria andClusterSourceLessThanOrEqualTo(String value) {
            addCriterion("cluster_source <=", value, "clusterSource");
            return (Criteria) this;
        }

        public Criteria andClusterSourceLike(String value) {
            addCriterion("cluster_source like", value, "clusterSource");
            return (Criteria) this;
        }

        public Criteria andClusterSourceNotLike(String value) {
            addCriterion("cluster_source not like", value, "clusterSource");
            return (Criteria) this;
        }

        public Criteria andClusterSourceIn(List<String> values) {
            addCriterion("cluster_source in", values, "clusterSource");
            return (Criteria) this;
        }

        public Criteria andClusterSourceNotIn(List<String> values) {
            addCriterion("cluster_source not in", values, "clusterSource");
            return (Criteria) this;
        }

        public Criteria andClusterSourceBetween(String value1, String value2) {
            addCriterion("cluster_source between", value1, value2, "clusterSource");
            return (Criteria) this;
        }

        public Criteria andClusterSourceNotBetween(String value1, String value2) {
            addCriterion("cluster_source not between", value1, value2, "clusterSource");
            return (Criteria) this;
        }

        public Criteria andClusterTypeIdIsNull() {
            addCriterion("cluster_type_id is null");
            return (Criteria) this;
        }

        public Criteria andClusterTypeIdIsNotNull() {
            addCriterion("cluster_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andClusterTypeIdEqualTo(Integer value) {
            addCriterion("cluster_type_id =", value, "clusterTypeId");
            return (Criteria) this;
        }

        public Criteria andClusterTypeIdNotEqualTo(Integer value) {
            addCriterion("cluster_type_id <>", value, "clusterTypeId");
            return (Criteria) this;
        }

        public Criteria andClusterTypeIdGreaterThan(Integer value) {
            addCriterion("cluster_type_id >", value, "clusterTypeId");
            return (Criteria) this;
        }

        public Criteria andClusterTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cluster_type_id >=", value, "clusterTypeId");
            return (Criteria) this;
        }

        public Criteria andClusterTypeIdLessThan(Integer value) {
            addCriterion("cluster_type_id <", value, "clusterTypeId");
            return (Criteria) this;
        }

        public Criteria andClusterTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("cluster_type_id <=", value, "clusterTypeId");
            return (Criteria) this;
        }

        public Criteria andClusterTypeIdIn(List<Integer> values) {
            addCriterion("cluster_type_id in", values, "clusterTypeId");
            return (Criteria) this;
        }

        public Criteria andClusterTypeIdNotIn(List<Integer> values) {
            addCriterion("cluster_type_id not in", values, "clusterTypeId");
            return (Criteria) this;
        }

        public Criteria andClusterTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("cluster_type_id between", value1, value2, "clusterTypeId");
            return (Criteria) this;
        }

        public Criteria andClusterTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cluster_type_id not between", value1, value2, "clusterTypeId");
            return (Criteria) this;
        }

        public Criteria andPrincipalIdIsNull() {
            addCriterion("principal_id is null");
            return (Criteria) this;
        }

        public Criteria andPrincipalIdIsNotNull() {
            addCriterion("principal_id is not null");
            return (Criteria) this;
        }

        public Criteria andPrincipalIdEqualTo(Long value) {
            addCriterion("principal_id =", value, "principalId");
            return (Criteria) this;
        }

        public Criteria andPrincipalIdNotEqualTo(Long value) {
            addCriterion("principal_id <>", value, "principalId");
            return (Criteria) this;
        }

        public Criteria andPrincipalIdGreaterThan(Long value) {
            addCriterion("principal_id >", value, "principalId");
            return (Criteria) this;
        }

        public Criteria andPrincipalIdGreaterThanOrEqualTo(Long value) {
            addCriterion("principal_id >=", value, "principalId");
            return (Criteria) this;
        }

        public Criteria andPrincipalIdLessThan(Long value) {
            addCriterion("principal_id <", value, "principalId");
            return (Criteria) this;
        }

        public Criteria andPrincipalIdLessThanOrEqualTo(Long value) {
            addCriterion("principal_id <=", value, "principalId");
            return (Criteria) this;
        }

        public Criteria andPrincipalIdIn(List<Long> values) {
            addCriterion("principal_id in", values, "principalId");
            return (Criteria) this;
        }

        public Criteria andPrincipalIdNotIn(List<Long> values) {
            addCriterion("principal_id not in", values, "principalId");
            return (Criteria) this;
        }

        public Criteria andPrincipalIdBetween(Long value1, Long value2) {
            addCriterion("principal_id between", value1, value2, "principalId");
            return (Criteria) this;
        }

        public Criteria andPrincipalIdNotBetween(Long value1, Long value2) {
            addCriterion("principal_id not between", value1, value2, "principalId");
            return (Criteria) this;
        }

        public Criteria andIsUseIsNull() {
            addCriterion("is_use is null");
            return (Criteria) this;
        }

        public Criteria andIsUseIsNotNull() {
            addCriterion("is_use is not null");
            return (Criteria) this;
        }

        public Criteria andIsUseEqualTo(Boolean value) {
            addCriterion("is_use =", value, "isUse");
            return (Criteria) this;
        }

        public Criteria andIsUseNotEqualTo(Boolean value) {
            addCriterion("is_use <>", value, "isUse");
            return (Criteria) this;
        }

        public Criteria andIsUseGreaterThan(Boolean value) {
            addCriterion("is_use >", value, "isUse");
            return (Criteria) this;
        }

        public Criteria andIsUseGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_use >=", value, "isUse");
            return (Criteria) this;
        }

        public Criteria andIsUseLessThan(Boolean value) {
            addCriterion("is_use <", value, "isUse");
            return (Criteria) this;
        }

        public Criteria andIsUseLessThanOrEqualTo(Boolean value) {
            addCriterion("is_use <=", value, "isUse");
            return (Criteria) this;
        }

        public Criteria andIsUseIn(List<Boolean> values) {
            addCriterion("is_use in", values, "isUse");
            return (Criteria) this;
        }

        public Criteria andIsUseNotIn(List<Boolean> values) {
            addCriterion("is_use not in", values, "isUse");
            return (Criteria) this;
        }

        public Criteria andIsUseBetween(Boolean value1, Boolean value2) {
            addCriterion("is_use between", value1, value2, "isUse");
            return (Criteria) this;
        }

        public Criteria andIsUseNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_use not between", value1, value2, "isUse");
            return (Criteria) this;
        }

        public Criteria andClusterIpIsNull() {
            addCriterion("cluster_ip is null");
            return (Criteria) this;
        }

        public Criteria andClusterIpIsNotNull() {
            addCriterion("cluster_ip is not null");
            return (Criteria) this;
        }

        public Criteria andClusterIpEqualTo(String value) {
            addCriterion("cluster_ip =", value, "clusterIp");
            return (Criteria) this;
        }

        public Criteria andClusterIpNotEqualTo(String value) {
            addCriterion("cluster_ip <>", value, "clusterIp");
            return (Criteria) this;
        }

        public Criteria andClusterIpGreaterThan(String value) {
            addCriterion("cluster_ip >", value, "clusterIp");
            return (Criteria) this;
        }

        public Criteria andClusterIpGreaterThanOrEqualTo(String value) {
            addCriterion("cluster_ip >=", value, "clusterIp");
            return (Criteria) this;
        }

        public Criteria andClusterIpLessThan(String value) {
            addCriterion("cluster_ip <", value, "clusterIp");
            return (Criteria) this;
        }

        public Criteria andClusterIpLessThanOrEqualTo(String value) {
            addCriterion("cluster_ip <=", value, "clusterIp");
            return (Criteria) this;
        }

        public Criteria andClusterIpLike(String value) {
            addCriterion("cluster_ip like", value, "clusterIp");
            return (Criteria) this;
        }

        public Criteria andClusterIpNotLike(String value) {
            addCriterion("cluster_ip not like", value, "clusterIp");
            return (Criteria) this;
        }

        public Criteria andClusterIpIn(List<String> values) {
            addCriterion("cluster_ip in", values, "clusterIp");
            return (Criteria) this;
        }

        public Criteria andClusterIpNotIn(List<String> values) {
            addCriterion("cluster_ip not in", values, "clusterIp");
            return (Criteria) this;
        }

        public Criteria andClusterIpBetween(String value1, String value2) {
            addCriterion("cluster_ip between", value1, value2, "clusterIp");
            return (Criteria) this;
        }

        public Criteria andClusterIpNotBetween(String value1, String value2) {
            addCriterion("cluster_ip not between", value1, value2, "clusterIp");
            return (Criteria) this;
        }

        public Criteria andClusterPortIsNull() {
            addCriterion("cluster_port is null");
            return (Criteria) this;
        }

        public Criteria andClusterPortIsNotNull() {
            addCriterion("cluster_port is not null");
            return (Criteria) this;
        }

        public Criteria andClusterPortEqualTo(Integer value) {
            addCriterion("cluster_port =", value, "clusterPort");
            return (Criteria) this;
        }

        public Criteria andClusterPortNotEqualTo(Integer value) {
            addCriterion("cluster_port <>", value, "clusterPort");
            return (Criteria) this;
        }

        public Criteria andClusterPortGreaterThan(Integer value) {
            addCriterion("cluster_port >", value, "clusterPort");
            return (Criteria) this;
        }

        public Criteria andClusterPortGreaterThanOrEqualTo(Integer value) {
            addCriterion("cluster_port >=", value, "clusterPort");
            return (Criteria) this;
        }

        public Criteria andClusterPortLessThan(Integer value) {
            addCriterion("cluster_port <", value, "clusterPort");
            return (Criteria) this;
        }

        public Criteria andClusterPortLessThanOrEqualTo(Integer value) {
            addCriterion("cluster_port <=", value, "clusterPort");
            return (Criteria) this;
        }

        public Criteria andClusterPortIn(List<Integer> values) {
            addCriterion("cluster_port in", values, "clusterPort");
            return (Criteria) this;
        }

        public Criteria andClusterPortNotIn(List<Integer> values) {
            addCriterion("cluster_port not in", values, "clusterPort");
            return (Criteria) this;
        }

        public Criteria andClusterPortBetween(Integer value1, Integer value2) {
            addCriterion("cluster_port between", value1, value2, "clusterPort");
            return (Criteria) this;
        }

        public Criteria andClusterPortNotBetween(Integer value1, Integer value2) {
            addCriterion("cluster_port not between", value1, value2, "clusterPort");
            return (Criteria) this;
        }

        public Criteria andClusterAccountIsNull() {
            addCriterion("cluster_account is null");
            return (Criteria) this;
        }

        public Criteria andClusterAccountIsNotNull() {
            addCriterion("cluster_account is not null");
            return (Criteria) this;
        }

        public Criteria andClusterAccountEqualTo(String value) {
            addCriterion("cluster_account =", value, "clusterAccount");
            return (Criteria) this;
        }

        public Criteria andClusterAccountNotEqualTo(String value) {
            addCriterion("cluster_account <>", value, "clusterAccount");
            return (Criteria) this;
        }

        public Criteria andClusterAccountGreaterThan(String value) {
            addCriterion("cluster_account >", value, "clusterAccount");
            return (Criteria) this;
        }

        public Criteria andClusterAccountGreaterThanOrEqualTo(String value) {
            addCriterion("cluster_account >=", value, "clusterAccount");
            return (Criteria) this;
        }

        public Criteria andClusterAccountLessThan(String value) {
            addCriterion("cluster_account <", value, "clusterAccount");
            return (Criteria) this;
        }

        public Criteria andClusterAccountLessThanOrEqualTo(String value) {
            addCriterion("cluster_account <=", value, "clusterAccount");
            return (Criteria) this;
        }

        public Criteria andClusterAccountLike(String value) {
            addCriterion("cluster_account like", value, "clusterAccount");
            return (Criteria) this;
        }

        public Criteria andClusterAccountNotLike(String value) {
            addCriterion("cluster_account not like", value, "clusterAccount");
            return (Criteria) this;
        }

        public Criteria andClusterAccountIn(List<String> values) {
            addCriterion("cluster_account in", values, "clusterAccount");
            return (Criteria) this;
        }

        public Criteria andClusterAccountNotIn(List<String> values) {
            addCriterion("cluster_account not in", values, "clusterAccount");
            return (Criteria) this;
        }

        public Criteria andClusterAccountBetween(String value1, String value2) {
            addCriterion("cluster_account between", value1, value2, "clusterAccount");
            return (Criteria) this;
        }

        public Criteria andClusterAccountNotBetween(String value1, String value2) {
            addCriterion("cluster_account not between", value1, value2, "clusterAccount");
            return (Criteria) this;
        }

        public Criteria andClusterDescriptionIsNull() {
            addCriterion("cluster_description is null");
            return (Criteria) this;
        }

        public Criteria andClusterDescriptionIsNotNull() {
            addCriterion("cluster_description is not null");
            return (Criteria) this;
        }

        public Criteria andClusterDescriptionEqualTo(String value) {
            addCriterion("cluster_description =", value, "clusterDescription");
            return (Criteria) this;
        }

        public Criteria andClusterDescriptionNotEqualTo(String value) {
            addCriterion("cluster_description <>", value, "clusterDescription");
            return (Criteria) this;
        }

        public Criteria andClusterDescriptionGreaterThan(String value) {
            addCriterion("cluster_description >", value, "clusterDescription");
            return (Criteria) this;
        }

        public Criteria andClusterDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("cluster_description >=", value, "clusterDescription");
            return (Criteria) this;
        }

        public Criteria andClusterDescriptionLessThan(String value) {
            addCriterion("cluster_description <", value, "clusterDescription");
            return (Criteria) this;
        }

        public Criteria andClusterDescriptionLessThanOrEqualTo(String value) {
            addCriterion("cluster_description <=", value, "clusterDescription");
            return (Criteria) this;
        }

        public Criteria andClusterDescriptionLike(String value) {
            addCriterion("cluster_description like", value, "clusterDescription");
            return (Criteria) this;
        }

        public Criteria andClusterDescriptionNotLike(String value) {
            addCriterion("cluster_description not like", value, "clusterDescription");
            return (Criteria) this;
        }

        public Criteria andClusterDescriptionIn(List<String> values) {
            addCriterion("cluster_description in", values, "clusterDescription");
            return (Criteria) this;
        }

        public Criteria andClusterDescriptionNotIn(List<String> values) {
            addCriterion("cluster_description not in", values, "clusterDescription");
            return (Criteria) this;
        }

        public Criteria andClusterDescriptionBetween(String value1, String value2) {
            addCriterion("cluster_description between", value1, value2, "clusterDescription");
            return (Criteria) this;
        }

        public Criteria andClusterDescriptionNotBetween(String value1, String value2) {
            addCriterion("cluster_description not between", value1, value2, "clusterDescription");
            return (Criteria) this;
        }

        public Criteria andClusterHostConfIsNull() {
            addCriterion("cluster_host_conf is null");
            return (Criteria) this;
        }

        public Criteria andClusterHostConfIsNotNull() {
            addCriterion("cluster_host_conf is not null");
            return (Criteria) this;
        }

        public Criteria andClusterHostConfEqualTo(String value) {
            addCriterion("cluster_host_conf =", value, "clusterHostConf");
            return (Criteria) this;
        }

        public Criteria andClusterHostConfNotEqualTo(String value) {
            addCriterion("cluster_host_conf <>", value, "clusterHostConf");
            return (Criteria) this;
        }

        public Criteria andClusterHostConfGreaterThan(String value) {
            addCriterion("cluster_host_conf >", value, "clusterHostConf");
            return (Criteria) this;
        }

        public Criteria andClusterHostConfGreaterThanOrEqualTo(String value) {
            addCriterion("cluster_host_conf >=", value, "clusterHostConf");
            return (Criteria) this;
        }

        public Criteria andClusterHostConfLessThan(String value) {
            addCriterion("cluster_host_conf <", value, "clusterHostConf");
            return (Criteria) this;
        }

        public Criteria andClusterHostConfLessThanOrEqualTo(String value) {
            addCriterion("cluster_host_conf <=", value, "clusterHostConf");
            return (Criteria) this;
        }

        public Criteria andClusterHostConfLike(String value) {
            addCriterion("cluster_host_conf like", value, "clusterHostConf");
            return (Criteria) this;
        }

        public Criteria andClusterHostConfNotLike(String value) {
            addCriterion("cluster_host_conf not like", value, "clusterHostConf");
            return (Criteria) this;
        }

        public Criteria andClusterHostConfIn(List<String> values) {
            addCriterion("cluster_host_conf in", values, "clusterHostConf");
            return (Criteria) this;
        }

        public Criteria andClusterHostConfNotIn(List<String> values) {
            addCriterion("cluster_host_conf not in", values, "clusterHostConf");
            return (Criteria) this;
        }

        public Criteria andClusterHostConfBetween(String value1, String value2) {
            addCriterion("cluster_host_conf between", value1, value2, "clusterHostConf");
            return (Criteria) this;
        }

        public Criteria andClusterHostConfNotBetween(String value1, String value2) {
            addCriterion("cluster_host_conf not between", value1, value2, "clusterHostConf");
            return (Criteria) this;
        }

        public Criteria andClusterConfSavePathIsNull() {
            addCriterion("cluster_conf_save_path is null");
            return (Criteria) this;
        }

        public Criteria andClusterConfSavePathIsNotNull() {
            addCriterion("cluster_conf_save_path is not null");
            return (Criteria) this;
        }

        public Criteria andClusterConfSavePathEqualTo(String value) {
            addCriterion("cluster_conf_save_path =", value, "clusterConfSavePath");
            return (Criteria) this;
        }

        public Criteria andClusterConfSavePathNotEqualTo(String value) {
            addCriterion("cluster_conf_save_path <>", value, "clusterConfSavePath");
            return (Criteria) this;
        }

        public Criteria andClusterConfSavePathGreaterThan(String value) {
            addCriterion("cluster_conf_save_path >", value, "clusterConfSavePath");
            return (Criteria) this;
        }

        public Criteria andClusterConfSavePathGreaterThanOrEqualTo(String value) {
            addCriterion("cluster_conf_save_path >=", value, "clusterConfSavePath");
            return (Criteria) this;
        }

        public Criteria andClusterConfSavePathLessThan(String value) {
            addCriterion("cluster_conf_save_path <", value, "clusterConfSavePath");
            return (Criteria) this;
        }

        public Criteria andClusterConfSavePathLessThanOrEqualTo(String value) {
            addCriterion("cluster_conf_save_path <=", value, "clusterConfSavePath");
            return (Criteria) this;
        }

        public Criteria andClusterConfSavePathLike(String value) {
            addCriterion("cluster_conf_save_path like", value, "clusterConfSavePath");
            return (Criteria) this;
        }

        public Criteria andClusterConfSavePathNotLike(String value) {
            addCriterion("cluster_conf_save_path not like", value, "clusterConfSavePath");
            return (Criteria) this;
        }

        public Criteria andClusterConfSavePathIn(List<String> values) {
            addCriterion("cluster_conf_save_path in", values, "clusterConfSavePath");
            return (Criteria) this;
        }

        public Criteria andClusterConfSavePathNotIn(List<String> values) {
            addCriterion("cluster_conf_save_path not in", values, "clusterConfSavePath");
            return (Criteria) this;
        }

        public Criteria andClusterConfSavePathBetween(String value1, String value2) {
            addCriterion("cluster_conf_save_path between", value1, value2, "clusterConfSavePath");
            return (Criteria) this;
        }

        public Criteria andClusterConfSavePathNotBetween(String value1, String value2) {
            addCriterion("cluster_conf_save_path not between", value1, value2, "clusterConfSavePath");
            return (Criteria) this;
        }

        public Criteria andServerIdIsNull() {
            addCriterion("server_id is null");
            return (Criteria) this;
        }

        public Criteria andServerIdIsNotNull() {
            addCriterion("server_id is not null");
            return (Criteria) this;
        }

        public Criteria andServerIdEqualTo(Integer value) {
            addCriterion("server_id =", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdNotEqualTo(Integer value) {
            addCriterion("server_id <>", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdGreaterThan(Integer value) {
            addCriterion("server_id >", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("server_id >=", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdLessThan(Integer value) {
            addCriterion("server_id <", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdLessThanOrEqualTo(Integer value) {
            addCriterion("server_id <=", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdIn(List<Integer> values) {
            addCriterion("server_id in", values, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdNotIn(List<Integer> values) {
            addCriterion("server_id not in", values, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdBetween(Integer value1, Integer value2) {
            addCriterion("server_id between", value1, value2, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("server_id not between", value1, value2, "serverId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdIsNull() {
            addCriterion("creater_id is null");
            return (Criteria) this;
        }

        public Criteria andCreaterIdIsNotNull() {
            addCriterion("creater_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreaterIdEqualTo(Long value) {
            addCriterion("creater_id =", value, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdNotEqualTo(Long value) {
            addCriterion("creater_id <>", value, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdGreaterThan(Long value) {
            addCriterion("creater_id >", value, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdGreaterThanOrEqualTo(Long value) {
            addCriterion("creater_id >=", value, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdLessThan(Long value) {
            addCriterion("creater_id <", value, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdLessThanOrEqualTo(Long value) {
            addCriterion("creater_id <=", value, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdIn(List<Long> values) {
            addCriterion("creater_id in", values, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdNotIn(List<Long> values) {
            addCriterion("creater_id not in", values, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdBetween(Long value1, Long value2) {
            addCriterion("creater_id between", value1, value2, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdNotBetween(Long value1, Long value2) {
            addCriterion("creater_id not between", value1, value2, "createrId");
            return (Criteria) this;
        }

        public Criteria andMenderIdIsNull() {
            addCriterion("mender_id is null");
            return (Criteria) this;
        }

        public Criteria andMenderIdIsNotNull() {
            addCriterion("mender_id is not null");
            return (Criteria) this;
        }

        public Criteria andMenderIdEqualTo(Long value) {
            addCriterion("mender_id =", value, "menderId");
            return (Criteria) this;
        }

        public Criteria andMenderIdNotEqualTo(Long value) {
            addCriterion("mender_id <>", value, "menderId");
            return (Criteria) this;
        }

        public Criteria andMenderIdGreaterThan(Long value) {
            addCriterion("mender_id >", value, "menderId");
            return (Criteria) this;
        }

        public Criteria andMenderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("mender_id >=", value, "menderId");
            return (Criteria) this;
        }

        public Criteria andMenderIdLessThan(Long value) {
            addCriterion("mender_id <", value, "menderId");
            return (Criteria) this;
        }

        public Criteria andMenderIdLessThanOrEqualTo(Long value) {
            addCriterion("mender_id <=", value, "menderId");
            return (Criteria) this;
        }

        public Criteria andMenderIdIn(List<Long> values) {
            addCriterion("mender_id in", values, "menderId");
            return (Criteria) this;
        }

        public Criteria andMenderIdNotIn(List<Long> values) {
            addCriterion("mender_id not in", values, "menderId");
            return (Criteria) this;
        }

        public Criteria andMenderIdBetween(Long value1, Long value2) {
            addCriterion("mender_id between", value1, value2, "menderId");
            return (Criteria) this;
        }

        public Criteria andMenderIdNotBetween(Long value1, Long value2) {
            addCriterion("mender_id not between", value1, value2, "menderId");
            return (Criteria) this;
        }

        public Criteria andRemoteUrlIsNull() {
            addCriterion("remote_url is null");
            return (Criteria) this;
        }

        public Criteria andRemoteUrlIsNotNull() {
            addCriterion("remote_url is not null");
            return (Criteria) this;
        }

        public Criteria andRemoteUrlEqualTo(String value) {
            addCriterion("remote_url =", value, "remoteUrl");
            return (Criteria) this;
        }

        public Criteria andRemoteUrlNotEqualTo(String value) {
            addCriterion("remote_url <>", value, "remoteUrl");
            return (Criteria) this;
        }

        public Criteria andRemoteUrlGreaterThan(String value) {
            addCriterion("remote_url >", value, "remoteUrl");
            return (Criteria) this;
        }

        public Criteria andRemoteUrlGreaterThanOrEqualTo(String value) {
            addCriterion("remote_url >=", value, "remoteUrl");
            return (Criteria) this;
        }

        public Criteria andRemoteUrlLessThan(String value) {
            addCriterion("remote_url <", value, "remoteUrl");
            return (Criteria) this;
        }

        public Criteria andRemoteUrlLessThanOrEqualTo(String value) {
            addCriterion("remote_url <=", value, "remoteUrl");
            return (Criteria) this;
        }

        public Criteria andRemoteUrlLike(String value) {
            addCriterion("remote_url like", value, "remoteUrl");
            return (Criteria) this;
        }

        public Criteria andRemoteUrlNotLike(String value) {
            addCriterion("remote_url not like", value, "remoteUrl");
            return (Criteria) this;
        }

        public Criteria andRemoteUrlIn(List<String> values) {
            addCriterion("remote_url in", values, "remoteUrl");
            return (Criteria) this;
        }

        public Criteria andRemoteUrlNotIn(List<String> values) {
            addCriterion("remote_url not in", values, "remoteUrl");
            return (Criteria) this;
        }

        public Criteria andRemoteUrlBetween(String value1, String value2) {
            addCriterion("remote_url between", value1, value2, "remoteUrl");
            return (Criteria) this;
        }

        public Criteria andRemoteUrlNotBetween(String value1, String value2) {
            addCriterion("remote_url not between", value1, value2, "remoteUrl");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andIsRunningIsNull() {
            addCriterion("is_running is null");
            return (Criteria) this;
        }

        public Criteria andIsRunningIsNotNull() {
            addCriterion("is_running is not null");
            return (Criteria) this;
        }

        public Criteria andIsRunningEqualTo(Boolean value) {
            addCriterion("is_running =", value, "isRunning");
            return (Criteria) this;
        }

        public Criteria andIsRunningNotEqualTo(Boolean value) {
            addCriterion("is_running <>", value, "isRunning");
            return (Criteria) this;
        }

        public Criteria andIsRunningGreaterThan(Boolean value) {
            addCriterion("is_running >", value, "isRunning");
            return (Criteria) this;
        }

        public Criteria andIsRunningGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_running >=", value, "isRunning");
            return (Criteria) this;
        }

        public Criteria andIsRunningLessThan(Boolean value) {
            addCriterion("is_running <", value, "isRunning");
            return (Criteria) this;
        }

        public Criteria andIsRunningLessThanOrEqualTo(Boolean value) {
            addCriterion("is_running <=", value, "isRunning");
            return (Criteria) this;
        }

        public Criteria andIsRunningIn(List<Boolean> values) {
            addCriterion("is_running in", values, "isRunning");
            return (Criteria) this;
        }

        public Criteria andIsRunningNotIn(List<Boolean> values) {
            addCriterion("is_running not in", values, "isRunning");
            return (Criteria) this;
        }

        public Criteria andIsRunningBetween(Boolean value1, Boolean value2) {
            addCriterion("is_running between", value1, value2, "isRunning");
            return (Criteria) this;
        }

        public Criteria andIsRunningNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_running not between", value1, value2, "isRunning");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sdps_cluster
     *
     * @mbg.generated do_not_delete_during_merge Fri Dec 24 15:33:19 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sdps_cluster
     *
     * @mbg.generated Fri Dec 24 15:33:19 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}