management:
  server:
    servlet:
      context-path: /actuator
  health:
    mail:
      enabled: false
spring:
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: "/static/**"
  resources:
    static-locations: "classpath:/static/"
  freemarker:
    templateLoaderPath: "classpath:/templates/"
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    settings.number_format: 0.##########
  datasource:
    url: jdbc:mysql://10.1.3.113:3306/sdps?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 900000
      connection-timeout: 10000
      connection-test-query: SELECT 1
      validation-timeout: 1000
  mail:
    host: smtp.qq.com
    port: 25
    username: 1130260281@qq.com
    from: 1130260281@qq.com
    password: jfqrtdxqinxxjecg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        socketFactory:
          class: javax.net.ssl.SSLSocketFactory
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml
#mybatis.type-aliases-package=com.xxl.job.admin.core.model
xxl:
  job:
    accessToken: 
    i18n: zh_CN
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100
    logretentiondays: 30
