spring:    
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://10.1.3.113:3306/sdps-7.2?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver
      druid:
        filters: stat,slf4j,wall
mybatis-plus:
  type-aliases-package: com.seaboxdata.spds.uaa.oauth.model
  mapper-locations:
    - classpath*:com/seaboxdata/sdps/uaa/oauth/mapper/*.xml


sdps:
  oauth2:
    token:
      store:
        type: redis
  security:
    cas:
      serverUrl: https://10.1.2.5:17003/cas
    code:
      # 忽略验证码的应用编号
      ignoreClientCode: app
    auth:
      # 开启统一登出
      unifiedLogout: false
      # 同账号登录互踢
      isSingleLogin: true  
      isShareToken: true
      onlyOneLogin: false
  #多租户配置
  tenant:
    enable: true
    ignoreTables:
      - oauth_client_details
aj:
  captcha:
    jigsaw: classpath:images/jigsaw
    pic-click: classpath:images/pic-click
    cache-type: redis
    type: default
#    water-mark: 
#    water-font: \u5b8b\u4f53
#    font-type: \u5b8b\u4f53
    slip-offset: 5
    aes-status: true
    interference-options: 1
    font-style: 1
    font-size: 25
    history-data-clear-enable: true
    req-frequency-limit-enable: true
    req-get-lock-limit: 5
    req-get-lock-seconds: 360
    req-get-minute-limit: 30
    req-check-minute-limit: 60
    req-verify-minute-limit: 60
