spring:    
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://10.1.3.113:3306/sdps-7.2?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver
      druid:
        filters: stat,slf4j,wall
  mail:
    resetPassUrl: http://10.1.3.114:9091/#
    host: smtp.qq.com
    username: 1130260281@qq.com
    password: jfqrtdxqinxxjecg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8

  #163 ok email demo2:
#  mail:
#    host: smtp.163.com
#    port: 25
#    username: xisijingluxi@163.com
#    #pop3协议设置密码 非邮箱密码
#    password: BTMV*******
#    protocol: smtp
#    default   -encoding: UTF-8
#    properties:
#      mail.smtp.auth: true
#      mail.smtp.starttls.enable: true
#      mail.smtp.starttls.required: true
#      mail.smtp.socketFactory.port: 465
#      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
#      mail.smtp.socketFactory.fallback: false
    emailFrom: xisijingluxi@163.com
#    resetPassUrl: http://10.1.0.180:9091/#

mybatis-plus:
  type-aliases-package: com.seaboxdata.sdps.common.core.model,com.seaboxdata.sdps.user.mybatis.model
  mapper-locations:
    - classpath*:com/seaboxdata/sdps/user/mybatis/mapper/*.xml
sdps:
  #多租户配置
  tenant:
    enable: true
    ignoreTables:
      - sys_role
      - sys_menu
    ignoreSqls:
      # 用户关联角色时，显示所有角色
      - com.seaboxdata.sdps.user.mybatis.mapper.SysRoleMapper.findRolesByExample
      - com.seaboxdata.sdps.user.mybatis.mapper.SysMenuMapper.selectList